version: "3.0"
services:
  aggregator:
    build: ..
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_ENDPOINT=https://api.mainnet-beta.solana.com

  redis:
    image: redislabs/rebloom # Redis with Rebloom module
    ports:
      - 6379:6379
