version: "3.0"
services:
  aggregator:
    build: ..
    ports:
      - 3000:3000
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redislabs/redismod
    ports:
      - 6379:6379
